Repository kgolezardi/Performance-Review-Web, pull requests merged in 2019-12, with the labels that each got.

#4 Feat/material ui
  package.json
  src/App.tsx
  src/_config/fonts.ts
  src/_config/install.ts
  src/core/rtl/RtlSupportProvider.tsx
  src/core/styles/GlobalStyles.tsx
  src/core/theme/themes.ts
  src/locales/en/messages.po
  src/locales/fa/messages.po
  src/shared/types/FCProps.ts
  src/shared/types/Styles.ts
  yarn.lock
Labels: enhancement

#13 feat(storybook-addon-language-selector)
  .storybook/addons.js
  .storybook/config.js
  package.json
  src/core/locales/languages.ts
  src/locales/en/messages.po
  src/locales/fa/messages.po
  src/shared/layouts/dashboard-layouts/DashboardLayout.stories.tsx
  src/stories/config-i18n-selector.ts
  src/stories/decorators/themeDecorator.tsx
  src/stories/direction-state.ts
  src/stories/helpers/DirectionState.ts
  src/stories/index.ts
  src/stories/sample.stories.tsx
  yarn.lock
Labels: enhancement

#34 fix(strengths-weaknesses-page): add initial value from server
  src/pages/strengths-weaknesses-page/StrengthsWeaknessesForm.tsx
  src/pages/strengths-weaknesses-page/StrengthsWeaknessesPage.tsx
  src/shared/utils/general.util.ts
Labels: enhancement

#38 Fix(criteria-form): add initial value from server
  src/pages/criteria-page/CriteriaForm.tsx
  src/pages/criteria-page/CriteriaPage.tsx
  src/shared/criterion-item/CriterionItem.tsx
Labels: enhancement

#39 fix(strengths-weaknesses-form): fix initialValue to be optional
  src/pages/strengths-weaknesses-page/StrengthsWeaknessesForm.tsx
Labels: enhancement

#41 fix(main-container): add full height to main container and it's spinner
  src/AppRouter.tsx
  src/shared/layouts/dashboard-layouts/DashboardLayout.tsx
  src/shared/loading/FullPageSpinner.tsx
Labels: enhancement

#44 feat(settings-provider): add settings provider to the project
  src/AppRouter.tsx
  src/core/settings/SettingsContext.tsx
  src/core/settings/SettingsProvider.tsx
  src/core/settings/index.ts
Labels: enhancement

#69 Add snackbar to projects
  package.json
  src/App.tsx
  src/core/snackbar/Snackbar.stories.tsx
  src/core/snackbar/SnackbarProvider.tsx
  src/core/snackbar/index.ts
  src/locales/en/messages.po
  src/locales/fa/messages.po
  src/pages/criteria-page/CriteriaPage.tsx
  src/pages/projects-page/ProjectsPage.tsx
  src/pages/strengths-weaknesses-page/StrengthsWeaknessesPage.tsx
  src/stories/decorators/SnackbarDecorator.tsx
  src/stories/decorators/index.ts
  yarn.lock
Labels: enhancement

#75 chore(error-page): Add proper error page
  src/locales/en/messages.po
  src/locales/fa/messages.po
  src/shared/error/OverlayError.stories.tsx
  src/shared/error/OverlayError.tsx
  src/shared/error/index.ts
  src/shared/full-page-error/FullPageError.stories.tsx
  src/shared/full-page-error/FullPageError.tsx
  src/shared/layouts/dashboard-layouts/DashboardLayout.tsx
  src/shared/overlay/Overlay.stories.tsx
  src/shared/overlay/Overlay.tsx
  src/shared/overlay/index.ts
Labels: enhancement

#94 Add guide-page
  package.json
  src/containers/main/MainContainer.tsx
  src/containers/main/MainRoutes.tsx
  src/locales/en/messages.po
  src/locales/fa/messages.po
  src/mdx.d.ts
  src/pages/guide-page/Content.mdx
  src/pages/guide-page/GuidePage.tsx
  yarn.lock
Labels: question

#109 feat(bi-di-snackbar): add BiDiSnackbar hook
  src/core/snackbar/Snackbar.stories.tsx
  src/core/snackbar/SnackbarProvider.tsx
  src/pages/criteria-page/CriteriaPage.tsx
  src/pages/projects-page/ProjectsPage.tsx
  src/pages/strengths-weaknesses-page/StrengthsWeaknessesPage.tsx
  src/shared/snackbar/index.ts
  src/shared/snackbar/useBiDiSnackbar.ts
Labels: bugfix, enhancement
