Repository kgolezardi/Performance-Review-Web, pull requests merged in 2020-02, with the labels that each got.

#178 fix(multiline-output): fix multiline output not having key in map
  src/shared/multiline-output/MultilineOutput.tsx
Labels: bugfix

#180 feat(project-manager-review): add project manager review component
  src/locales/en/messages.po
  src/locales/fa/messages.po
  src/shared/project-manager-review/ProjectManagerReview.stories.tsx
  src/shared/project-manager-review/ProjectManagerReview.tsx
  src/shared/project-manager-review/index.ts
  src/shared/project-manager-review/types.d.ts
Labels: enhancement

#186 chore(creteria-manager-review): add creteria manager review component…
  src/locales/en/messages.po
  src/locales/fa/messages.po
  src/shared/criteria-manager-review/CriteriaManagerReview.stories.tsx
  src/shared/criteria-manager-review/CriteriaManagerReview.tsx
  src/shared/criteria-manager-review/index.ts
  src/shared/criterion-output-item/CriterionOutputItem.stories.tsx
  src/shared/criterion-output-item/CriterionOutputItem.tsx
  src/shared/criterion-output-item/index.ts
Labels: enhancement

#187 fix(criteria-manager-review): export it's props
  src/shared/criteria-manager-review/CriteriaManagerReview.tsx
  src/shared/criteria-manager-review/types.d.ts
Labels: bugfix

#188 chore(manager-review-content): complete manager review content
  src/locales/en/messages.po
  src/locales/fa/messages.po
  src/pages/manager-review-page/ManagerReviewContent.tsx
  src/pages/manager-review-page/ManagerReviewPage.tsx
  src/pages/manager-review-page/useCurrentPersonReview.ts
  src/pages/manager-review-page/useCurrentProjectReviews.ts
  src/shared/project-manager-review/ProjectManagerReview.stories.tsx
Labels: enhancement

#190 chore(storybook): update storybook to version 5.3.10
  .storybook/addons.js
  .storybook/main.js
  .storybook/preview.js
  .storybook/webpack.config.js
  .travis.yml
  package.json
  src/stories/config-i18n-selector.ts
  src/stories/index.ts
  yarn.lock
Labels: enhancement

#196 fix(charasteristics-output): fix characteristics key index
  src/pages/manager-review-page/CharacteristicsOutput.tsx
Labels: bugfix

#201 Fix/evaluation output
  src/shared/criterion-output-item/CriterionOutputItem.tsx
  src/shared/evaluation-output/EvaluationOutput.stories.tsx
  src/shared/evaluation-output/EvaluationOutput.tsx
  src/shared/project-manager-review/ProjectManagerReview.tsx
Labels: bugfix

#199 chore(criterion-output-item): add criterion peer review output item
  src/shared/project-peer-reveiw-output/ProjectPeerReviewOutput.stories.tsx
  src/shared/project-peer-reveiw-output/ProjectPeerReviewOutput.tsx
  src/shared/project-peer-reveiw-output/index.ts
Labels: enhancement

#202 fix(project-peer-review-output): fix remaining problems in #199 cmnts
  src/shared/project-peer-reveiw-output/ProjectPeerReviewOutput.tsx
Labels: enhancement

#203 fix(storybook): fix source loader not working correctly
  .storybook/main.js
Labels: bugfix

#211 chore(project-peer-review): add project peer review components
  schema.graphql
  src/locales/en/messages.po
  src/locales/fa/messages.po
  src/pages/projects-page/ProjectForm.tsx
  src/pages/projects-page/ProjectsPage.tsx
  src/pages/projects-page/deleteProjectReview.mutation.ts
  src/shared/criterion-item/CriterionItem.stories.tsx
  src/shared/evaluation-output/EvaluationOutput.tsx
  src/shared/multiline-output/MultilineOutput.tsx
  src/shared/project-peer-reveiw-output/ProjectPeerReviewOutput.stories.tsx
  src/shared/project-peer-review-form/ProjectPeerReviewForm.stories.tsx
  src/shared/project-peer-review-form/ProjectPeerReviewForm.tsx
  src/shared/project-peer-review-form/index.ts
  src/shared/project-peer-review-form/types.d.ts
  src/shared/project-peer-review-item/ProjectPeerReviewItem.stories.tsx
  src/shared/project-peer-review-item/ProjectPeerReviewItem.tsx
  src/shared/project-peer-review-item/index.ts
  src/shared/project-peer-review-item/saveProjectComment.mutation.ts
  src/shared/project-peer-review-output/ProjectPeerReviewOutput.stories.tsx
  src/shared/project-peer-review-output/ProjectPeerReviewOutput.tsx
  src/shared/project-peer-review-output/index.ts
  src/stories/decorators/index.ts
  src/stories/decorators/promptDecorator.tsx
Labels: bugfix, enhancement

#218 feat(project-comment-page): add project comment page
  src/pages/peer-review-page/PeerReviewPage.tsx
  src/pages/project-comment-page/Guide.mdx
  src/pages/project-comment-page/ProjectCommentPage.tsx
  src/pages/project-comment-page/index.ts
Labels: enhancement

#217 chore(section-guide-story): add storybook for section guide
  src/shared/section-guide/SectionGuide.stories.tsx
Labels: enhancement

#219 fix(peer-review-page): fix margin between tab and form
  src/pages/peer-review-page/PeerReviewPage.tsx
Labels: enhancement

#227 User avatar component
  src/locales/en/messages.po
  src/locales/fa/messages.po
  src/pages/peer-review-board-page/PeerReviewBoardPage.tsx
  src/pages/peer-review-page/PersonInfoCard.tsx
  src/shared/board-list/BoardList.stories.tsx
  src/shared/user-avatar/UserAvatar.tsx
  src/shared/user-avatar/index.ts
  src/shared/user-card/UserCard.stories.tsx
  src/shared/user-card/UserCard.tsx
Labels: enhancement

#236 chore(mdx-js__react): add proper types for MDXContext and everything else
  src/mdx-js__react.d.ts
  src/mdx.d.ts
  src/pages/criteria-page/CriteriaForm.tsx
  src/pages/guide-page/GuideCard.tsx
  src/pages/project-comment-page/ProjectCommentPage.tsx
  src/pages/projects-page/ProjectsPage.tsx
  src/pages/start-review-page/StartReviewCard.tsx
  src/pages/strengths-weaknesses-page/StrengthsWeaknessesForm.tsx
Labels: bugfix, enhancement

#245 fix(anys): remove anys from projects where possible
  src/mdx-js__react.d.ts
  src/pages/dashboard-page/DominantCharacteristicsCircularIndicator.tsx
  src/pages/manager-review-page/ManagerReviewContent.tsx
  src/pages/start-review-page/start-review.mutation.ts
  src/shared/criterion-item/CriterionItem.tsx
  src/shared/error-boundary/ErrorBoundary.tsx
  src/shared/layouts/dashboard-layouts/DashboardLayout.tsx
  src/shared/mdx-provider/MDXPropsProvider.tsx
  src/shared/mdx-provider/MDXProvider.tsx
  src/shared/tab/TabPanel.tsx
  src/shared/tab/TabPanels.tsx
  src/shared/tabs/Tabs.tsx
  src/shared/utils/withProps.tsx
Labels: enhancement

#246 fix(imports): fix whole project imports
  src/App.tsx
  src/AppRouter.tsx
  src/core/locales/languages.ts
  src/core/rtl/RtlSupportProvider.tsx
  src/core/snackbar/SnackbarProvider.tsx
  src/core/styles/GlobalStyles.tsx
  src/core/theme/themes.ts
  src/pages/dashboard-page/DashboardPage.tsx
  src/pages/dashboard-page/LinkButton.tsx
  src/pages/dashboard-page/ProjectProgress.tsx
  src/pages/guide-page/GuidePage.tsx
  src/pages/guide-page/NvcGuidePage.tsx
  src/pages/start-review-page/PeerStartReviewPage.tsx
  src/pages/start-review-page/SelfStartReviewPage.tsx
  src/pages/strengths-weaknesses-page/StrengthsWeaknessesPage.tsx
  src/shared/auth/Login.tsx
  src/shared/confirm-button/ConfirmButton.tsx
  src/shared/confirm-provider/ConfirmationDialog.tsx
  src/shared/criteria-output/CriteriaOutput.tsx
  src/shared/danger-button/DangerButton.tsx
  src/shared/forminator/inputs/LimitedTextAreaInput.tsx
  src/shared/forminator/inputs/SelectAutoComplete.tsx
  src/shared/forminator/inputs/SelectMultiAutoComplete.tsx
  src/shared/forminator/inputs/StringInput.tsx
  src/shared/forminator/inputs/array-input/ArrayAppendButton.tsx
  src/shared/forminator/inputs/array-input/ArrayRemoveButton.tsx
  src/shared/forminator/utils/SubmitButton.tsx
  src/shared/in-view/InView.stories.tsx
  src/shared/in-view/InView.tsx
  src/shared/layouts/dashboard-layouts/Brand.tsx
  src/shared/layouts/dashboard-layouts/DashboardLayout.tsx
  src/shared/layouts/dashboard-layouts/menu/NavBarMenu.tsx
  src/shared/layouts/dashboard-layouts/menu/NavBarMenuItem.tsx
  src/shared/loading/FullPageSpinner.tsx
  src/shared/members-list/MembersListItem.tsx
  src/shared/output-border/OutputBorder.tsx
  src/shared/project-output/ProjectCommentsOutput.tsx
  src/shared/project-output/ProjectOutput.tsx
  src/shared/project-peer-review-output/ProjectPeerReviewOutput.stories.tsx
  src/shared/select/Select.stories.tsx
  src/shared/sticky-action-bar/ActionBar.tsx
  src/shared/sticky-action-bar/StickyActionBar.tsx
  src/shared/tab/TabLink.tsx
  src/shared/text-link/TextLink.tsx
  src/shared/types/Styles.ts
  src/stories/config-i18n-selector.ts
  src/stories/decorators/StoryWrapperDecorator.tsx
  src/stories/decorators/TransparentBackground.tsx
  src/stories/decorators/themeDecorator.tsx
  src/stories/direction-state.ts
  src/stories/helpers/DirectionState.ts
Labels: bugfix, enhancement
